### PR TITLE
Optimized the progress line and scroll animations (with steps animation to fix animation jittering up).

### PR DESCRIPTION
**Pull request by Kvnq-Poza**
Removed observer (and useEffect) and used Framer Motion for all animations.

Used custom easing curves using cubic-bezier for smoother motion.

Created helper functions (better maintainability) for content mapping rather than repetitive JSX.

This should fix the progress line smoothness, jittering, and make the progress line more performant.

### CODE REVIEW

**Comment by niangamadou888** [comment]
He wanted the line to stop at 5 and not to continue... Did you show him?

**Comment by Kvnq-Poza** [comment]
All I was told was it wasn't displaying correctly.

So, the progress line shouldn't be displayed for the other components??

**Comment by niangamadou888** [comment]
photo_2024-12-24 21 01 45
i think you was supposed to work on this he want the line to continue under the text and finish at the middle not the buy steps line it's already done

**Comment by Kvnq-Poza** [comment]
Ok
The line should end pointing at the button.

Noted.

I'll check it out.

**Comment by niangamadou888** [comment]
yeah exactly

**Pull request merged**
